apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-color-rs
  labels:
    app: web-color
spec:
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: web-color